#+HTML_HEAD: <link href='http://fonts.googleapis.com/css?family=Merriweather:400,400italic,900&subset=latin-ext,latin' rel='stylesheet' type='text/css'>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/stylesheet.css" />

#+TITLE: Oświata w Gminie Kołaczkowo do r.1980 (szkic monograficzny).
#+AUTHOR: Aniceta Kubisiak

#+BEGIN_ABSTRACT

Motto ---

#+BEGIN_QUOTE
My potrafimy karmić dusze milionów własnymi sercami, ale sami zawsze
na próżno łakniemy odrobiny szczęścia.

-- Władysław St.Reymont
#+END_QUOTE

*Oświata w Gminie Kołaczkowo do r.1980 (szkic monograficzny).*

#+BEGIN_QUOTE
ocalić od zapomnienia
#+END_QUOTE

--- cytatem z "Pieśni" Gałczyńskiego nazwaliśmy naszą gazetkę
szkolną. Pragniemy utrwalić w pamięci mieszkańców Gminy i naszych
uczniów bardzo pobieżną historię szkół i nauczycieli - ludzi, którzy
swoje życie poświęcili dla kształtowania dusz ludzkich na tym
terenie. Dysponujemy bardzo skąpym materiałem faktograficznym
dotyczącym rozwoju oświaty i szkolnictwa. Postawą opracowania szkicu
monograficznego były kroniki szkół; wywiady przeprowadzone z
mieszkańcami poszczególnych wsi.

Kroniki szkół są niekompletne, a w niektórych placówkach uległy
zupełnemu zniszczeniu podczas okupacji. Być może, że w wykazach
nauczycieli w poszczególnych miejscowościach, są również pewne luki
(brak lub zniekształcenie nazwisk).

Jednak to, co zawarte jest w tej gazetce, pozwoli chociaż częściowo
zachować pamięć o tych miejscach i tych ludziach, którzy są najmilszym
wspomnieniem z czasów dzieciństwa i młodości każdego człowieka.

/Aniceta Kubisiak/
#+END_ABSTRACT


* Szkoła w Kołaczkowie

/Aniceta Kubisiak/

Według historycznych źródeł szkoła w Kołaczkowie istniała już w 1695
r. Trudno jest jednak zlokalizować miejsce, gdzie przez okres dwóch
wieków odbywały się zajęcia lekcyjne. Wiadomo natomiast, że od roku
1898 szkoła mieściła się w budynku probostwa.

[Zdjęcie]

Ponieważ budynek ten uległ zniszczeniu, dziedzic zgodził się, aby
jedną salę w pałacu oddać na potrzeby nauki szkolnej. W 1906
r. przeniesiono szkołę do Łagiewek i tam przez okres 8 lat uczęszczały
dzieci z Kołaczkowa i okolicznych wiosek. Taki stan trwał do roku
1914 --- wybuchu I wojny światowej.

[Zdjęcie]

Właściwe powstanie szkoły datuje się z chwilą wyzwolenia Ojczyzny w
1918 r. Wówczas to w budynku Komisariatu Policji zlokalizowano szkołę
polską. Była to w okresie międzywojennym szkoła jednoklasowa o 1
nauczycielu. Dzieci kończyły na miejscu 3 lub 4 klasy a następnie
uczęszczały do Wszemborza.

[Zdjęcie]

Rok 1939, rok nieszczęścia i klęski Narodu Polskiego, powoduje
zamknięcie polskiej szkoły. W zimie 1940 r. utworzona zostaje szkoła
dla dzieci niemieckich, która istniała do 1945 r.

Po wyzwoleniu Ojczyzny spod okupacji hitlerowskiej szkoła polska
powstaje na nowo. Przez pierwszy rok istniały tylko klasy I i II, a od
1946 r. klasy I--IV. Klasę V wprowadzono w 1956 r., a VI i VII w
następnych latach.

2 listopada 1961 r. zorganizowano Szkołę Przysposobienia Rolniczego,
która przygotowywała kwalifikowane kadry do rolnictwa przez okres 13
lat.

Uroczystość wmurowania aktu erekcyjnego pod budowę nowej szkoły odbyła
się 21 listopada 1964 r., natomiast uroczystość oddania budynku do
użytku datuje się na 29 sierpnia 1965 r. W roku szkolnym 1966.67
wprowadzono klasę ósmą.

[Zdjęcie]

Imię Władysława Reymonta nadano szkole 7 maja 1967 r. W dniu ty
dokonano odsłonięcia tablicy pamiątkowej poświęconej Patronowi Szkoły.

[Zdjęcie]

W związku z reorganizacją administracji państwowej w 1973 r. powołano
Gminnego Dyrektora Szkół, natomiast Zbiorcza Szkoła Gminna w
Kołaczkowie powstała w 1974 r. Wydarzeniem w działalności Zbiorowej
Szkoły Gminnej im. Władysława Reymonta w Kołaczkowie było zdobycie i
wręczenie sztandaru 6 maja 1978 r.

** Nauczyciele szkoły w Kołaczkowie w latach 1918--1980

1. Cebulski
2. Gondelowa
3. Tesarowa
4. Duczniak K
5. Suchorski
6. Parchimowiczówna St.
7. Urbańska Jadwiga
8. Pachela Józef
9. Metler Henryk
10. Kaziemierczak Irena
11. Murawiecki Franciszek
12. Murawiecka Ludwika
13. Pera Józef
14. Prause Maria
15. Urbaniak Henryka
16. Hauke Maria
17. Olszewska Henryka
18. Koralewska Danuta
19. Wiśniewska Elżbieta
20. Królikowski Zbigniew
21. Pilarska Janina
22. Gałuszewska Marianna
23. Dobrowolski Bogdan
24. Dobrowolska Bolesława
25. Dąbrowska Renata
26. Jaśkiewicz Halina
27. Jakubowski Marek
28. Korzeniewska Danuta
29. Kubisiak Aniceta
30. Sczaniecka Jadwiga
31. Starosta Halina
32. Tomczak Jerzy
33. Łukasik Władysław
34. Rymarska Jadwiga
35. Jakubowska Bożena
36. Nowacka Halina
37. Walczak Maria
38. Lisiecka Stefania
39. Łukasik Alina
40. Cieślak Zofia
41. Hauke Mieczysław
42. Owsińska Mirosława
43. Antkowiak Stanisław
44. Rachubiński Rafał

** Nauczyciele Szkoły Przysposobienia Rolniczego
1. Miszczuk Jadwiga
2. Małolepszy Marian
3. Koralewska Małgorzata
4. Koralewski Roman
5. Szablikowski Lechosław

* Szkoła w Borzykowie

/Aniceta Kubisiak/

Zbyt mało materiałów źródłowych istnieje na naszym terenie, aby można
było przedstawić dawniejsze dzieje szkoły w Borzykowie. Z przekazów
ustnych dowiadujemy się, że obecny budynek szkolny został zbudowany w
1912 r. Była to szkoła 4--klasowa o 2 nauczycielach. Uczyło tu
małżeństwo Zgolińskich. Ostatnim nauczycielem przed 1939 r. był
Kantel, który zabrany przez Niemców, zginął w obozie. W okresie
okupacji szkoła była zamknięta dla dzieci polskich.

Po wyzwoleniu z wielkim entuzjazmem zaczęto organizować
szkolnictwo. Uroczyste otwarcie Publicznej Szkoły w Borzykowie
nastąpiło 5 lutego 1945 r. Do szkoły zgłosiło się 65 dzieci w różnym
wieku i ze zróżnicowanym stopniem przygotowania do podjęcia nauki:
utworzono klasy I--IV. Przy pomocy rodziców i dzieci wykonano sztandar
szkolny, którego wręczenie nastąpiło w kwietniu 1945 r. Od września
1947 r. wprowadzono klasę V, a rok później klasę VI. Ze względu na
małą ilość dzieci obniżono w r. 1950 stopień organizacji do klas
I--IV.

Do klas starszych dzieci uczęszczały do Wszemborza. Ponownie klasę V
wprowadzono w 1956 r., w 1957 r. klasę VI, w 1958 klasę VII i w 1965
r. klasę VIII. Taki stan trwał do roku 1969. Od 1 września tego roku
uczniowie kl. V-VIII uczęszczali do szkół we Wszemborzu, Kołaczkowie,
Pyzdrach.

Na podkreślenie zasługuje postawa społeczeństwa Borzykowa, jego
serdeczny stosunek do szkoły, zaangażowanie i wszechstronna pomoc
okazana w ciągu całego istnienia placówki.

** Nauczyciele uczący w Borzykowie w latach 1945--1980

1. Pogodziński Stanisław, 5.II.1945--1946
2. Liebthalówna Prakseda, 1945
3. Galantówna Władysława, 1945
4. Umiński Zdzisław, 1946--1950
5. Umińska Zofia, 1946--1950
6. Daroszewska Waleria, 1950--1959
7. Świtajska Maria, 1956
8. Pawlik Stanisław, 1957
9. Stelmach Marian, 1958--1969
10. Stelmach Jadwiga, 1958
11. Pera Józef, 1959--1961
12. Filipczak Bożena, 1959--1960
13. Pera Małgorzata, 1960--1961
14. Nagórska Jadwiga, 1961--1963
15. Budziński Jerzy, 1962--1963
16. Nowacka Halina, 1963
17. Knasiak Jadwiga, 1963--1965
18. Sakowski Andrzej, 1965
19. Waszak Barbara, 1966
20. Kruczkowska Wanda, 1967
21. Ilska Helena, 1967--1968
22. Koralewska Zofia, 1968

* Szkoła w Gorazdowie

/Aniceta Kubisiak/

W mroku dziejów trudno ustalić datę powstania szkoły. Faktem jest, że
istniała, a znajdowała się, według relacji mieszkańców, w budynku
glinianym na działce szkolnej przy drodze prowadzącej do
Sokolnik. Obecny budynek oddano do użytku w roku 1889. Nauka odbywała
się w języku niemieckim, a język polski uwzględniono jako przedmiot
nadobowiązkowy. Strajk dzieci wrzesińskich odbił się głośny echem w
całej Polsce, również dzieci w Gorazdowie buntowały się przeciwko
nauczaniu religii w języku niemieckim.

Po odzyskaniu niepodległości w 1918 r. powstaje szkoła
polska. Początkowo są cztery klasy i uczy jeden nauczyciel. Później
przydzielono drugą silę nauczycielską i zorganizowano klasę piątą.

Z chwilą zajęcia Gorazdowa przez wojska hitlerowskie w 1939 r. szkołę
likwiduje się. Akta szkoły ulegają zniszczeniu. Sprzęt szkolny,
biblioteka i pomoce naukowe okupant wywozi do szkół niemieckich lub
niszczy na miejscu. W szkole kwateruje najpierw wojsko niemieckie,
potem żandarmeria. Następnie zorganizowano tu ośrodek naprawy maszyn,
a w szkole osiedlono robotników.

Po okupacji niemieckiej szkoła przedstawia obraz okropnego
zniszczenia. Okna bez szyb, ściany brudne, brak jakiegokolwiek sprzętu
brak książek i zeszytów. W ciężkich warunkach zorganizowano sześć
klas, a do klasy VII dzieci uczęszczają do Sokolnik. Klasę siódmą
wprowadzono od 1 września 1948 r. W tym czasie uczy trzech
nauczycieli.

W latach pięćdziesiątych szczególnie uciążliwa dla pracy dydaktycznej
jest ciasnota pomieszczeń. Korzysta się z wypożyczonych sal
zastępczych w miejscowym pałacu. Z inicjatywy ludności i władz
powstaje Społeczny Komitet Rozbudowy Szkoły. Ze względu na trudności
obiektywne nie zrealizowano idei rozbudowy szkoły. Trudności narastają
wraz z wprowadzeniem klasy ósmej w 1966 r. Brakuje mieszkań dla
nauczycieli.

W roku 1974 uczy w Szkole Podstawowej w Gorazdowie 7 nauczycieli. Jest
to ostatni rok istnienia szkoły, bowiem z dniem 1 września 1974
r. szkoła 8-klasowa zostaje zlikwidowana, pozostają 4 klasy, a na jej
miejsce powstaje Punkt Filialny w Gorazdowie o 3 nauczycielach. Dzieci
z klas starszych dowożone są do Zbiorczej Szkoły Gminnej w
Kołaczkowie. W 1978 r. obniżono stopień organizacyjny do 3 klas.

** Nauczyciele szkoły w Gorazdowie w latach 1889--1980

1. Nelke
2. Pady
3. Knape
4. Berkoffe, 1914 r.
5. Szafarek, 1918 r.
6. Górska
7. Papieżówna
8. Rybarski, 1921-1939, Kierownik Szkoły
9. Szafarek Aleksander, 13.III.1945, Kierownik Szkoły
10. Szafarek Wanda, 13.III.1945--1.IX.1946, Kierownik Szkoły
11. Gramzel, I-III.1946
12. Wnuk Kazimierz, III--VI.1946
13. Olędzki Paweł, 1.IX.1946--1.IX.1967, Kierownik Szkoły
14. Olędzka Antonina, 1.IX.1946--1.IX.1967
15. Rogalska Maria, 1966-1969
16. Szepelak Zdzisław, 1949
17. Bartkowiak Wanda, do 1953
18. Andrzejczak Cecylia, 1953--1955
19. Bogusz Roman, 1955--1956
20. Kowalewski Zygmunt, 1955--1956, 1958--1960
21. Pera Józef, 1955--1958
22. Kubisiak Aniceta, 1956--1974, Dyrektor Szkoły w latach 1969--1974
23. Nowacka Irena, 1958--1959
24. Pruszak Regina, 1960--1968
25. Aleksandrowicz Irena, 1963--1968
26. Kucharska Ryszarda, 1966--1967
27. Złotnik Halina, 1966--1968
28. Walczak Maria, 1968--1975, Kierownik punktu filialnego w latach 1975--1976
29. Smętkowska Anna, 1968--1970
30. Jakubowska Bożena, 1968--1976
31. Jakubowski Marek, 1968--1974
32. Łukasik Alina, 1969--1975, Kierownik punktu filialnego w latach 1074--1975
33. Dąbrowska Renata, 1969--1973
34. Ławniczak Weronika, 1970--1971
35. Łukasik Władysław, 1970--1974
36. Helwing Zofia, 1976, Kierownik punktu filialnego
37. Szalaty Maria, 1979
38. Helak Danuta, 1980

[Zdjęcie]

* Szkoła we Wszemborzu

/Stefania Lisiecka/

Czas założenia pierwszej szkoły we Wszemborzu nie dał się
ustalić. Pewnym jest tylko, że już około 1840 roku szkoła we
Wszemborzu istniała. Przypuszczać należy, że pierwsza szkoła powstała
w pierwszych dziesiątkach lat dziewiętnastego wieku. Pierwszy budynek
szkolny budowany był z gliny i kryty słomą. Stał on na miejscu, gdzie
obecnie jest ogród szkolny, frontem do drogi.

Nowy, obecny budynek szkolny został wzniesiony w roku 1895. Jest to
budynek piętrowy, murowany z cegły, kryty dachówką, stoi szczytem do
drogi. W pierwszym okresie istnienia znajdowały się w nim dwie sale
lekcyjne, pozostałą cześć zajmowało dwóch nauczycieli. Była to wówczas
publiczna szkoła powszechna pierwszego stopnia o dwóch nauczycielach.

Z początkiem roku szkolnego 1935/36 uzyskano zezwolenie władz
szkolnych na podniesienie stopnia organizacyjnego szkoły na publiczną
szkołę powszechną o trzech nauczycielach. Trzecią izbę lekcyjną
uzyskano z dwóch pokoi nauczycielskich. W związku z podniesieniem
stopnia organizacyjnego, szkoła stała się szkołą zbiorczą dla
okolicznych gromad. Uczęszczały do niej dzieci z Borzykowa,
Kołaczkowa, Budziłowa, Łagiewek, Spławia, a niekiedy z Nowej Wsi
Podgórnej i z Mikuszewa. W takim stanie doczekała szkoła 1 września
1939 roku.

10 września 1939 roku w budynku szkolnym zakwaterowali żołnierze
niemieccy. Zerwali oni ze ściany frontowe godło i napis. Spalili też
wówczas bibliotekę i akta szkolne. W miesiącach letnich 1940 roku
otworzyli Niemcy w tym budynku szkołę niemiecką wyłącznie dla dzieci
niemieckich. W dniu 22 stycznia 1945 roku do Wszemborza przybyło
wojsko radzieckie. Żołnierze ci odpoczywali i nocowali w budynku
szkolnym.

Przez okres wojny budynek został zaniedbany i zniszczony. Przy pomocy
młodzieży szkolnej budynek został uporządkowany i oczyszczony. W dniu
12 lutego 1945 roku dokonano otwarcia polskiej szkoły. Młodzież
szkolną podzielono na podstawie prowizorycznego egzaminu z czytania,
pisania i rachunków na cztery klasy.

W dniu 1 kwietnia z 13 najlepszych uczniów utworzono klasę piątą W
roku szkolnym 1945/46 w szkole było już 6 klas a w
następnym 7. Pracowało w niej 4 nauczycieli. Taki stan utrzymywał się
do roku 1966. W latach 1966--1974 była to szkoła 8-klasowa, początkowo
o 5-ciu nauczycielach, potem o 6-ciu. Obecnie jest to punk filialny
Zbiorczej Szkoły Gminnej w Kołaczkowie z klasami I--III.

[Zdjęcie]

** Nauczyciele szkoły we Wszemborzu w latach 1918--1980

1. Kahl, do 1919
2. Machałowski Józef, 1919/1920
3. Śrokówna Janina, 1920--1933
4. Srokówna Zofia, 1920--1933
5. Sadowski Jan, od 1 lipca 1933
6. Sauer Klemens, 1933-1937
7. Japhówna Julianna, 1936
8. Tessarowa Stefania, od 1936
9. Kulczak Franciszek, 1936-1937
10. Sadowski Jan, 1945
11. Suchorski Edmund, 1945--1946
12. Gizelska Bonifacja, 1945
13. Tessarowa Stefania, 1945--1949
14. Libthalówna Prakseda, 1946--1948
15. Galant Władysława, 1947/1948
16. Pilarska Janina, od 1948
17. Furmaniakówna Krystyna, od 1949
18. Malentowicz Stanisław, od 1949
19. Pachela Józef, od 1950
20. Zgoliński Feliks, od 1950
21. Budzińska Eugenia, od 1950
22. Skalewska Zofia, 1950--1953
23. Kaczmarkiewicz Czesława, 1951/1952
24. Grajek Wacław, do 1955
25. Winter Maria, 1951/1952
26. Szmytkowska Alina, od 1954
27. Depczyńska Bożena, od 1954
28. Szymański Henryk, 1955/1956
29. Tamborska Bożena, 1956/1957
30. Pera Józef, od 1961
31. Pera Małgorzata, od 1961
32. Prymas Anna
33. Lisiecka Stefania, 1966-1974
34. Rymarska Jadwiga, od 1967
35. Przybylska Zofia
36. Helwing Zofia
37. Korzeniewska Danuta

* Szkoła w Zielińcu

/Halina Starosta/

Pierwsze wzmianki o istnieniu szkoły w Zielińcu pochodzą z
1695r. Następne dane o szkole mamy dopiero z roku 1899, kiedy to na
okres 5 lat wynajęte zostały w Zielińcu dwie izby --- na klasę:
mieszkanie dla nauczyciela. 75 dzieci uczących się do tej pory w
Powszechnej Szkole w Bieganowie przeszło do Zielińca. Ponieważ jednak
szkoły w Zielińcu nie wybudowano, dzieci wróciły do Bieganowa. Po
długoletnich staraniach wybudowano w Zielińcu w 1911 nową
szkołę. Koszt budowy wyniósł 19 600 ml. Pierwszym nauczycielem został
p. Dojnakowski.

W okresie I wojny światowej \/1914--1918\/ nauka odbywała się
nieregularnie --- co drugi dzień dojeżdżał nauczyciel z Bieganowa. Do
roku 1952 nauczyciele kilkakrotnie zmieniali się. W 1932 r objął
posadę nauczyciela w szkole p. Józef Szafraniak, który uczył do
1950r. --- z przerwą w okresie wojennym.

Na terenie szkoły istniały w tym czasie różne organizacje uczniowskie:
- Koło Samorządu Szkolnego
- Koło L.O.P.P
- Koło PCK
- Spółdzielnia uczniowska "Iskierka"

Podczas okupacji 1939--1945r. szkołę przeznaczono dla dzieci
niemieckich.

W czasie okupacji zaginęły wszystkie księgi, akta, obrazy, książki,
pomoce naukowe i pieczęć szkolna. Sztandar szkoły oraz godło zdołano
przechować i przekazano je pierwszemu nauczycielowi, który po wojnie
podjął pracę w szkole.

Naukę rozpoczęto ponownie 1 kwietnia 1945r. W tym roku istniały trzy
klasy I, II, III, w których uczyło się 63 uczniów. Starsze dzieci
uczęszczały do zbiorczych szkół w Gozdowie i Skolonikach.

Szkoła nie posiadała biblioteki, dopiero po zbiórce pieniężnej i
zakupie książek 16.I.1949r. otworzono punkt biblioteczny.

W roku szkolnym 1962/63 szkoła w Zielińcu została podniesiona do
stopnia szkoły o dwóch nauczycielach. Powstały dalsze klasy III i
IV. Dzieci uczyły się w klasach łączonych II z III, IV z V. Pierwsza
klasa nie była łączona. Do 1964r., szkoła nie miała światła
elektrycznego. Dopiero w czerwcu 1964r. przeprowadzono elektryfikacje
części wsi, a wraz z nią szkoły.

Dzieci z Zielińca uczęszczały do Szkoły Podstawowej w Gozdowie,
dopiero od roku 1977 dowozi się je do Zbiorczej Szkoły Gminnej w
Kołaczkowie. Szkoła w Zielińcu jest Punktem Filialnym o klasach
I--III.

[Zdjęcie]

[Zdjęcie]

** Nauczyciele szkoły w Zielińcu w latach 1910--1980

1. Linke Stefan, 1899
2. Donajkowski, 1914
3. Piątkowski, 1914--1918
4. Tomecki, 1918--1924
5. Kemmitz, 1924--1926
6. Kamińska, 1926
7. Woźniak Julian, 1927--1932
8. Szafraniak Józef, 1932--1939, 1.IV.1946--1.IX.1950, Kierownik
   Szkoły
9. Wnuk Kazimierz, 1.IV.1945--1.IV.1946
10. Sadowski Jan, 1.IX.1950--31.XII.1965, Kierownik Szkoły
11. Sobolewski Czesław, 1.IX.1962--2.XI.1963
12. Wasicka Jadwiga, 1.II.1964--31.VIII.1965
13. Szulc Adam, I.IX.1965, Kierownik Szkoły
14. Szulc Eleonora, 1.IX.1965
15. Tasiemska Sabina, 1.IX.1974, Kierownik Szkoły
16. Ciosek Barbara, 1978--1980
17. Rachubińska Karina, 20.VIII.1980

* Szkoła w Sokolnikach

/Marek Jakubowski/

Pierwsze zapiski o miejscowości Sokolniki pochodzą z
roku 1286. Natomiast pierwsza wzmianka o szkole w Sokolnikach datuje
się z roku 1692. Brak dokładnych danych od 1692 do 1880 nie pozwala
nam na dokładniejsze prześledzenie rozwoju szkoły w tym okresie na
terenie Sokolnik. Wiadomo na pewno, że od roku 1880 w Sokolnikach
istniała szkoła z językiem wykładowym niemieckim.

Działo się tak do roku 1928, kiedy to z inicjatywy nauczycieli dawnego
powiatu wrzesińskiego przeniesiono dotychczasową niemiecką szkołę na
szkołę polską. Dnia 1 maja 1919 roku nastąpiło oficjalne unarodowienie
szkół. Dzieci sokolnickie z chęcią garnęły się do polskiej nauki. Z
zapałem słuchały dziejów ojczystych. Wkrótce zniknęły z młodych
umysłów wszelkie ślady germanizacji.

Od samego początku przystąpiono z zapałem do pracy. W 1921 roku
młodzież z Sokolnik przekazała 6100mk na założenie biblioteki w
Sokolnikach.  Dnia 9 czerwca 1925r. młodzież tejże szkoły wyjeżdża na
pierwszą wycieczkę do Poznania, żadne z dzieci nie widziało jeszcze
kolei żelaznej, nie jechało pociągiem. W Poznaniu zwiedziły miasto,
ZOO i ogród botaniczny.

Or doku 1925 istniały w Sokolnikach 2 jednoklasowe szkoły. Jedna w
Sokolnikach z językiem wykładowym polskim a druga w Sokolnikach
Kolonii z językiem wykładowym niemieckim. W roku 1933/34 nastąpiło
połączenie tych szkół w jedną dwuklasową publiczną szkołę powszechną z
językiem wykładowym polskim.

Dzięki przychylności władz szkolnych w roku 1935 podniesiony został
stopień organizacyjny szkoły na szkołę II stopnia (6
oddziałową). Powiększono obwód szkolny przez włączenie części
Gałęzewic zwanych Gałęzewice Kolonia. Do szkoły w Sokolnikach
uczęszczały dzieci ze starszych roczników z innych sąsiednich obwodów
szkolnych, z Szamarzewa, Gorazdowa. Planowano w następnych latach
podnieść stopień organizacyjny szkoły do III stopnia czyli do
siedmioklasowej szkoły. Wiązało się to jednak z koniecznością budowy
dróg, aby dzieci z innych obwodów mogły do Sokolnik dojechać i z
koniecznością rozbudowy szkoły. W tym celu powstała nawet w
Sokolnikach Spółka Drogowa, która wybudowała drogę z Sokolnik do
Szamarzewa (2200m).

Aby poprawić warunki lokalowe postanowiono sprzedać jeden budynek
szkolny i za uzyskane pieniądze rozbudować drugi. Do celów rozbudowy
wypalono w 1939 roku 60.000 sztuk cegły. Niestety wybuch II wojny
światowej zniweczył te zamierzenia. Wypaloną cegłę w czasie wojny
rozebrali miejscowi Niemcy.

Od 1939 r. do 1945 nastąpiła przerwa w nauce. Ale już 8 lutego 1945
r. rozpoczęła się w Sokolnikach nauka. Tego dnia do szkoły zapisało
się około 100 dzieci. Jest to szkoła zbiorcza siedmioklasowa. Dnia 30
maja 1945 roku uroczyście dokonano otwarcia szkoły polskiej po
wojnie. W szkole uczyło 3 nauczycieli a uczęszczało do niej już 151
dzieci. W następnym roku szkolnym 1945/46 do szkoły uczęszczało 260
dzieci i uczyło 6 nauczycieli. Nauka odbywała się tylko w 2 salach
szkolnych i w izbach mieszkalnych zamienionych czasowo na izby
lekcyjne.

W 1946 roku postanowiono przebudować dawny sobór poewangelicki i
urządzić tam 2 izby lekcyjne. Pieniądze na przebudowę zebrano z
dobrowolnych ofiar mieszkańców Sokolnik, Gałęzewic, Szamarzewa,
Bieganowa, Graboszewa, Młodziejewic oraz z uzyskanych dochodów z
imprez. Łącznie na ten cel zebrano 61.000 zł. Dnia 29 września 1946
roku zakończono przebudowę i oddano użytku dwie nowe izby lekcyjne.

Na terenie szkoły we wrześniu 1945r. zorganizowano dwie organizacje
młodzieżowe --- PCK i ZHP. Były to pierwsze organizacje uczniowskie
działające w powojennej szkole w Sokolnikach. W listopadzie 1945 roku
zorganizowano Spółdzielnię Uczniowską.

Dnia 22 listopada 1945 roku zostaje wmurowany w ściany budynku
szkolnego pamiątkowa tablica dla uczczenia ofiar barbarzyństwa
hitlerowskiego z gromady Sokolniki.

Od 1 kwietnia 1945 r. przy szkole czynny jest Kurs Oświaty
Dorosłych. Na zakończenie roku szkolnego w 1946 roku Spółka Łowiecka
zakupiła dla szkoły warsztat stolarski za sumę 10.00 zł. Był to
pierwszy bardziej cenny dar przekazany szkole.

W 1948 roku szkoła uzyskała dodatkowo jeszcze jedną salę lekcyjną w
budynku gminnym oraz jedno mieszkanie nauczycielskie.

Dnia 5 kwietnia 1949 roku w miejsce dawnej Opieki Rodzicielskiej
zostaje powołany Komitet Rodzicielski.

Dnia 16 listopada 1952 r. odbyła się uroczystość wręczenia sztandaru
organizacji harcerskiej.

W latach 1950 -- 1976 szkoła w Sokolnikach mieściła się w 3
budynkach szkolnych i posiadała 5 izb lekcyjnych. Przez kilka lat
uczono w budynku gminnym. Była tam jedna klasa. W roku 1966 zostaje
utworzona VIII klasa. W roku szkolnym 1974/75 zostaje do szkoły w
Sokolnikach włączona młodzież ze szkoły w Szamarzewie,

W 1976 roku szkoła w Sokolnikach ulega likwidacji. Wszystkie klasy
zostają przeniesione do jednego budynku w Szamarzewie. W jednym z
budynków szkolnych zostaje utworzone przedszkole oraz mieszkanie dla
nauczyciela.

  [Zdjęcie][Dawny budynek szkolny. Obecnie siedziba przedszkola.]

Budynek szkolny za mleczarnią został przebudowany i zamieniony na
mieszkania dla nauczycieli.

  [Zdjęcie][Dawny budynek szkolny. Obecnie dom nauczyciela.]

** Nauczyciele szkoły w Sokolnikach

*** Lata 1890 -- 1939

1. Biczysko Kazimierz
2. Biczyskówna Pelagia
3. Grynia Franciszek
4. Mikołajczak
5. Felczak Kazimierz
6. Gibowski
7. Rogoziński
8. Wróblewska Franciszka
9. Hamerski Bolesław
10. Pogłodziński Stanisław

*** Lata 1945 -- 1950

11. [@11] Galantówna Władysława
12. Marciniak Józef
13. Rosicka Hanna
14. Parchimowicz Stanisława
15. Tomczak Bogusława
16. Broniecki Jan
17. Konczewska Tekla
18. Urbańska Jadwiga
19. Gryka Apolonia
20. Gryka Jan
21. Kozłowska Barbara
22. Winiecka Kornelia
23. Pruszkowski Bolesław

*** Lata 1950 -- 1976

24. [@24] Pera Józef
25. Umińska Zofia
26. Umiński Zdzisław
27. Bogusz Roman
28. Sierakowski Henryk
29. Miśkowiak Irena
30. Kazimierczak Michalina
31. Andrzejczak Cecylia
32. Jóźwiak Hieronim
33. Pacyńska Barbara
34. Wojciechowska Kazimiera
35. Potasińska Mirosława
36. Stolarska Jadwiga
37. Paprocka Jadwiga
38. Wróblewska Halina
39. Pocztarek Jan
40. Chojnacka Stefania
41. Głowacka Aleksandra
42. Maciejewski Jan
43. otylewska Aleksandra
44. Lisiak Anna
45. Skadłubowicz Anna
46. Sakowska Janina
47. Sakowski Andrzej
48. Jakubowski Marek
49. Marcinak Henryka
50. Antkowiak Stanisław

* Szkoła w Grabowie Królewskim

/Zbigniew Królikowski/

Pierwsze wzmianki dotyczące oświaty w Grabowie Królewskim pochodzą z 1965
roku. Tyle mówią stare dokumenty, dalsze dzieje zapisane zostały w kronice
szkoły. Dalsze, a nowe dzieje szkoły rozpoczynają się około roku 1840. Uczono
wówczas w gościńcu na tzw. Wygodzie.

W latach 1906 -- 1907 wybudowano nowy budynek szkoły, w którym do chwili
obecnej mieści się szkoła.

W latach międzywojennych (1918 -- 1929) szkoła była dwuklasowa. Początkowo
(1918 -- 1920) zajęcia odbywały się nieregularnie, prowadzone przez
dochodzącego z Zielińca nauczyciela. W następnych latach uczy w szkole dwóch
nauczycieli, a później trzech i czterech. W tym pierwszym okresie (1920
-- 1939) funkcję kierownika szkoły pełniła Józefa Piekarczykówna.

Rok 1939 --- tragiczny dla narodu, szkolnictwa i nauczycieli. 30 listopada
1939 roku nauczycielki (Piekarczykówna i Golachowska) zostały wywiezione do
Radomia, a budynek szkoły zamknięto. W taki sposób zaczęła się noc okupacyjna
dla oświaty w Grabowie.

Po wielu latach koszmaru nadszedł radosny zimowy dzień 21 stycznia 1945 ---
Grabowo było wolne. Wszyscy zdawali sobie sprawę z utraconych lat, kiedy nie
można było się uczyć.

Już 15 lutego rozpoczęto naukę. Brakowało wszystkiego sprzętu, podręczników,
pomocy naukowych i ciepła (brak szyb, pieców itp.). Nie brakowało jednego ---
zapału. Nad organizacją szkoły pieczę sprawował nauczyciel Aleksander
Woźniak. I tak w trudzie i znoju odrodziła się stara, ale nowa w charakterze
szkoła --- w państwie ludowym.

We wrześniu 1945 roku stanowisko kierownika szkoły objął Melchior
Korytowski. Człowiek ten to współczesna historia szkoły w Grabowie. Przez 26
lat dbał i czuwał nad grabowską szkołą --- do ostatnich chwil swego
nauczycielskiego życia. Za Jego czasów w latach 1957--1960 dokonano rozbudowy
szkoły --- poprawiły się warunki nauczycieli, ale tylko niektórzy "zawarli ze
szkołą ślub" jak chociażby p.p. Zofia Michalewska (od 1946 -- do chwili
obecnej), Janina Pilarska (od 1950).

Wraz z rozwojem państwa i oświaty rozwijała się i szkoła w Grabowie. W 1946
r. "rozrosła się" o klasy IV i V, w następnym o VI, a w 1948r. o
VII. Wspomniana wyżej rozbudowa szkoły w czynie społecznym bardzo się przydała
kiedy w 1966 roku doszła jeszcze klasa VIII.

Szkoła to nie tylko budynki to przede wszystkim ludzie, którzy dają "twarz"
szkole. Pełne oddanie kadry nauczycielskiej powodowało, że była ona dobrze
oceniana przez wizytacje szkolne. Może same wizytacje nie są tak ważne, bo
ważniejsze jest chyba to, że wśród uczniów, ukończyli szkołę w Grabowie w
latach 1945 -- 1976 (794 uczniów) 24 osoby posiadają wyższe wykształcenie, a
około 100 to absolwenci liceów ogólnokształcących i techników, wśród
pozostałych bardzo wielu ukończyło szkoły zawodowe różnych typów. Jednym z
tych 24 jest obecny Gminny Dyrektor Szkół mgr matematyki Bogdan Dobrowolski.

Szkoła to nie tylko nauka --- to również praca wychowawcza. W całej historii
szkoły spotykamy się z różnorodną działalnością wychowawczą prowadzoną przez
PCK, ZHP, LOK oraz inne organizacje i koła zainteresowań.

Chcąc mówić dziś o szkole w Grabowie w żadnym wymiarze nie można jej
przyrównywać do czasów minionych. Dziś jest to pełna ośmioklasowa szkoła o 7
nauczycielach kierowana przez dyrektora mgr. Franciszka Murawieckiego. Szkoła
posiada bibliotekę o 2325 tomach i dysponuje pomocami naukowymi za sumę około
400 tys. złotych.

Życzymy zatem na przyszłość dalszego rozowju tej szkole o tak długiej i dobrej
tradycji.

[zdjęcie]

* Szkoła w Szamarzewie

/Bogdan Dobrowolski/

* Szkoła w Bieganowie

/Mirosława Owsińska/

* Szkoła w Gałęzewicach

/Halina Jaśkiewicz/
