

* Szkoła w Kołaczkowie

Aniceta Kubisiak

Według historycznych źródeł szkoła w Kołaczkowie istniała już w 1695
r. Trudno jest jednak zlokalizować miejsce, gdzie przez okres dwóch
wieków odbywały się zajęcia lekcyjne. Wiadomo natomiast, że od roku
1898 szkoła mieściła się w budynku probostwa.

[Zdjęcie]

Ponieważ budynek ten uległ zniszczeniu, dziedzic zgodził się, aby
jedną salę w pałacu oddać na potrzeby nauki szkolnej. W 1906
r. przeniesiono szkołę do Łagiewek i tam przez okres 8 lat uczęszczały
dzieci z Kołaczkowa i okolicznych wiosek. Taki stan trwał do roku
1914 --- wybuchu I wojny światowej.

[Zdjęcie]

Właściwe powstanie szkoły datuje się z chwilą wyzwolenia Ojczyzny w
1918 r. Wówczas to w budynku Komisariatu Policji zlokalizowano szkołę
polską. Była to w okresie międzywojennym szkoła jednoklasowa o 1
nauczycielu. Dzieci kończyły na miejscu 3 lub 4 klasy a następnie
uczęszczały do Wszemborza.

[Zdjęcie]

Rok 1939, rok nieszczęścia i klęski Narodu Polskiego, powoduje
zamknięcie polskiej szkoły. W zimie 1940 r. utworzona zostaje szkoła
dla dzieci niemieckich, która istniała do 1945 r.

Po wyzwoleniu Ojczyzny spod okupacji hitlerowskiej szkoła polska
powstaje na nowo. Przez pierwszy rok istniały tylko klasy I i II, a od
1946 r. klasy I--IV. Klasę V wprowadzono w 1956 r., a VI i VII w
następnych latach.

2 listopada 1961 r. zorganizowano Szkołę Przysposobienia Rolniczego,
która przygotowywała kwalifikowane kadry do rolnictwa przez okres 13
lat.

Uroczystość wmurowania aktu erekcyjnego pod budowę nowej szkoły odbyła
się 21 listopada 1964 r., natomiast uroczystość oddania budynku do
użytku datuje się na 29 sierpnia 1965 r. W roku szkolnym 1966.67
wprowadzono klasę ósmą.

[Zdjęcie]

Imię Władysława Reymonta nadano szkole 7 maja 1967 r. W dniu ty
dokonano odsłonięcia tablicy pamiątkowej poświęconej Patronowi Szkoły.

[Zdjęcie]

W związku z reorganizacją administracji państwowej w 1973 r. powołano
Gminnego Dyrektora Szkół, natomiast Zbiorcza Szkoła Gminna w
Kołaczkowie powstała w 1974 r. Wydarzeniem w działalności Zbiorowej
Szkoły Gminnej im. Władysława Reymonta w Kołaczkowie było zdobycie i
wręczenie sztandaru 6 maja 1978 r.

** Nauczyciele szkoły w Kołaczkowie w latach 1918-1980

1. Cebulski
2. Gondelowa
3. Tesarowa
4. Duczniak K
5. Suchorski
6. Parchimowiczówna St.
7. Urbańska Jadwiga
8. Pachela Józef
9. Metler Henryk
10. Kaziemierczak Irena
11. Murawiecki Franciszek
12. Murawiecka Ludwika
13. Pera Józef
14. Prause Maria
15. Urbaniak Henryka
16. Hauke Maria
17. Olszewska Henryka
18. Koralewska Danuta
19. Wiśniewska Elżbieta
20. Królikowski Zbigniew
21. Pilarska Janina
22. Gałuszewska Marianna
23. Dobrowolski Bogdan
24. Dobrowolska Bolesława
25. Dąbrowska Renata
26. Jaśkiewicz Halina
27. Jakubowski Marek
28. Korzeniewska Danuta
29. Kubisiak Aniceta
30. Sczaniecka Jadwiga
31. Starosta Halina
32. Tomczak Jerzy
33. Łukasik Władysław
34. Rymarska Jadwiga
35. Jakubowska Bożena
36. Nowacka Halina
37. Walczak Maria
38. Lisiecka Stefania
39. Łukasik Alina
40. Cieślak Zofia
41. Hauke Mieczysław
42. Owsińska Mirosława
43. Antkowiak Stanisław
44. Rachubiński Rafał

** Nauczyciele Szkoły Przysposobienia Rolniczego
1. Miszczuk Jadwiga
2. Małolepszy Marian
3. Koralewska Małgorzata
4. Koralewski Roman
5. Szablikowski Lechosław


* Szkoła w Borzykowie

Aniceta Kubisiak


* Szkoła w Gorazdowie

Aniceta Kubisiak


* Szkoła we Wszemborzu

Stefania Lisiecka


* Szkoła w Zielińcu

Halina Starosta


* Szkoła w Sokolnikach

Marek Jakubowski


* Szkoła w Grabowie Królewskim

Zbigniew Królikowski


* Szkoła w Szamarzewie

Bogdan Dobrowolski

* Szkoła w Bieganowie

Mirosława Owsińska

* Szkoła w Gałęzewicach

Halina Jaśkiewicz
