* Motto --- 

#+BEGIN_QUOTE
My potrafimy karmić dusze milionów własnymi sercami, ale sami zawsze
na próżno łakniemy odrobiny szczęścia.

-- Władysław St.Reymont
#+END_QUOTE

Oświata w Gminie Kołaczkowo do r.1980 (szkic monograficzny).

#+BEGIN_QUOTE
ocalić od zapomnienia
#+END_QUOTE

--- cytatem z "Pieśni" Gałczyńskiego nazwaliśmy naszą gazetkę
szkolną. Pragniemy utrwalić w pamięci mieszkańców Gminy i naszych
uczniów bardzo pobieżną historię szkół i nauczycieli - ludzi, którzy
swoje życie poświęcili dla kształtowania dusz ludzkich na tym
terenie. Dysponujemy bardzo skąpym materiałem faktograficznym
dotyczącym rozwoju oświaty i szkolnictwa. Postawą opracowania szkicu
monograficznego były kroniki szkół; wywiady przeprowadzone z
mieszkańcami poszczególnych wsi.

Kroniki szkół są niekompletne, a w niektórych placówkach uległy
zupełnemu zniszczeniu podczas okupacji. Być może, że w wykazach
nauczycieli w poszczególnych miejscowościach, są również pewne luki
(brak lub zniekształcenie nazwisk).

Jednak to, co zawarte jest w tej gazetce, pozwoli chociaż częściowo
zachować pamięć o tych miejscach i tych ludziach, którzy są najmilszym
wspomnieniem z czasów dzieciństwa i młodości każdego człowieka.

Aniceta Kubisiak

* Szkoła w Kołaczkowie

Aniceta Kubisiak

Według historycznych źródeł szkoła w Kołaczkowie istniała już w 1695
r. Trudno jest jednak zlokalizować miejsce, gdzie przez okres dwóch
wieków odbywały się zajęcia lekcyjne. Wiadomo natomiast, że od roku
1898 szkoła mieściła się w budynku probostwa.

[Zdjęcie]

Ponieważ budynek ten uległ zniszczeniu, dziedzic zgodził się, aby
jedną salę w pałacu oddać na potrzeby nauki szkolnej. W 1906
r. przeniesiono szkołę do Łagiewek i tam przez okres 8 lat uczęszczały
dzieci z Kołaczkowa i okolicznych wiosek. Taki stan trwał do roku
1914 --- wybuchu I wojny światowej.

[Zdjęcie]

Właściwe powstanie szkoły datuje się z chwilą wyzwolenia Ojczyzny w
1918 r. Wówczas to w budynku Komisariatu Policji zlokalizowano szkołę
polską. Była to w okresie międzywojennym szkoła jednoklasowa o 1
nauczycielu. Dzieci kończyły na miejscu 3 lub 4 klasy a następnie
uczęszczały do Wszemborza.

[Zdjęcie]

Rok 1939, rok nieszczęścia i klęski Narodu Polskiego, powoduje
zamknięcie polskiej szkoły. W zimie 1940 r. utworzona zostaje szkoła
dla dzieci niemieckich, która istniała do 1945 r.

Po wyzwoleniu Ojczyzny spod okupacji hitlerowskiej szkoła polska
powstaje na nowo. Przez pierwszy rok istniały tylko klasy I i II, a od
1946 r. klasy I--IV. Klasę V wprowadzono w 1956 r., a VI i VII w
następnych latach.

2 listopada 1961 r. zorganizowano Szkołę Przysposobienia Rolniczego,
która przygotowywała kwalifikowane kadry do rolnictwa przez okres 13
lat.

Uroczystość wmurowania aktu erekcyjnego pod budowę nowej szkoły odbyła
się 21 listopada 1964 r., natomiast uroczystość oddania budynku do
użytku datuje się na 29 sierpnia 1965 r. W roku szkolnym 1966.67
wprowadzono klasę ósmą.

[Zdjęcie]

Imię Władysława Reymonta nadano szkole 7 maja 1967 r. W dniu ty
dokonano odsłonięcia tablicy pamiątkowej poświęconej Patronowi Szkoły.

[Zdjęcie]

W związku z reorganizacją administracji państwowej w 1973 r. powołano
Gminnego Dyrektora Szkół, natomiast Zbiorcza Szkoła Gminna w
Kołaczkowie powstała w 1974 r. Wydarzeniem w działalności Zbiorowej
Szkoły Gminnej im. Władysława Reymonta w Kołaczkowie było zdobycie i
wręczenie sztandaru 6 maja 1978 r.

** Nauczyciele szkoły w Kołaczkowie w latach 1918--1980

1. Cebulski
2. Gondelowa
3. Tesarowa
4. Duczniak K
5. Suchorski
6. Parchimowiczówna St.
7. Urbańska Jadwiga
8. Pachela Józef
9. Metler Henryk
10. Kaziemierczak Irena
11. Murawiecki Franciszek
12. Murawiecka Ludwika
13. Pera Józef
14. Prause Maria
15. Urbaniak Henryka
16. Hauke Maria
17. Olszewska Henryka
18. Koralewska Danuta
19. Wiśniewska Elżbieta
20. Królikowski Zbigniew
21. Pilarska Janina
22. Gałuszewska Marianna
23. Dobrowolski Bogdan
24. Dobrowolska Bolesława
25. Dąbrowska Renata
26. Jaśkiewicz Halina
27. Jakubowski Marek
28. Korzeniewska Danuta
29. Kubisiak Aniceta
30. Sczaniecka Jadwiga
31. Starosta Halina
32. Tomczak Jerzy
33. Łukasik Władysław
34. Rymarska Jadwiga
35. Jakubowska Bożena
36. Nowacka Halina
37. Walczak Maria
38. Lisiecka Stefania
39. Łukasik Alina
40. Cieślak Zofia
41. Hauke Mieczysław
42. Owsińska Mirosława
43. Antkowiak Stanisław
44. Rachubiński Rafał

** Nauczyciele Szkoły Przysposobienia Rolniczego
1. Miszczuk Jadwiga
2. Małolepszy Marian
3. Koralewska Małgorzata
4. Koralewski Roman
5. Szablikowski Lechosław


* Szkoła w Borzykowie

Aniceta Kubisiak

Zbyt mało materiałów źródłowych istnieje na naszym terenie, aby można
było przedstawić dawniejsze dzieje szkoły w Borzykowie. Z przekazów
ustnych dowiadujemy się, że obecny budynek szkolny został zbudowany w
1912 r. Była to szkoła 4--klasowa o 2 nauczycielach. Uczyło tu
małżeństwo Zgolińskich. Ostatnim nauczycielem przed 1939 r. był
Kantel, który zabrany przez Niemców, zginął w obozie. W okresie
okupacji szkoła była zamknięta dla dzieci polskich.

Po wyzwoleniu z wielkim entuzjazmem zaczęto organizować
szkolnictwo. Uroczyste otwarcie Publicznej Szkoły w Borzykowie
nastąpiło 5 lutego 1945 r. Do szkoły zgłosiło się 65 dzieci w różnym
wieku i ze zróżnicowanym stopniem przygotowania do podjęcia nauki:
utworzono klasy I--IV. Przy pomocy rodziców i dzieci wykonano sztandar
szkolny, którego wręczenie nastąpiło w kwietniu 1945 r. Od września
1947 r. wprowadzono klasę V, a rok później klasę VI. Ze względu na
małą ilość dzieci obniżono w r. 1950 stopień organizacji do klas
I--IV.

Do klas starszych dzieci uczęszczały do Wszemborza. Ponownie klasę V
wprowadzono w 1956 r., w 1957 r. klasę VI, w 1958 klasę VII i w 1965
r. klasę VIII. Taki stan trwał do roku 1969. Od 1 września tego roku
uczniowie kl. V-VIII uczęszczali do szkół we Wszemborzu, Kołaczkowie,
Pyzdrach.

Na podkreślenie zasługuje postawa społeczeństwa Borzykowa, jego
serdeczny stosunek do szkoły, zaangażowanie i wszechstronna pomoc
okazana w ciągu całego istnienia placówki.

** Nauczyciele uczący w Borzykowie w latach 1945--1980

1. Pogodziński Stanisław, 5.II.1945--1946
2. Liebthalówna Prakseda, 1945
3. Galantówna Władysława, 1945
4. Umiński Zdzisław, 1946--1950
5. Umińska Zofia, 1946--1950
6. Daroszewska Waleria, 1950--1959
7. Świtajska Maria, 1956
8. Pawlik Stanisław, 1957
9. Stelmach Marian, 1958--1969
10. Stelmach Jadwiga, 1958
11. Pera Józef, 1959--1961
12. Filipczak Bożena, 1959--1960
13. Pera Małgorzata, 1960--1961
14. Nagórska Jadwiga, 1961--1963
15. Budziński Jerzy, 1962--1963
16. Nowacka Halina, 1963
17. Knasiak Jadwiga, 1963--1965
18. Sakowski Andrzej, 1965
19. Waszak Barbara, 1966
20. Kruczkowska Wanda, 1967
21. Ilska Helena, 1967--1968
22. Koralewska Zofia, 1968

* Szkoła w Gorazdowie

Aniceta Kubisiak


* Szkoła we Wszemborzu

Stefania Lisiecka


* Szkoła w Zielińcu

Halina Starosta


* Szkoła w Sokolnikach

Marek Jakubowski


* Szkoła w Grabowie Królewskim

Zbigniew Królikowski


* Szkoła w Szamarzewie

Bogdan Dobrowolski

* Szkoła w Bieganowie

Mirosława Owsińska

* Szkoła w Gałęzewicach

Halina Jaśkiewicz
